# Generated by Django 3.1.4 on 2021-04-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
        migrations.RemoveField(
            model_name='rentbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rentbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LibUser',
        ),
        migrations.DeleteModel(
            name='RentBook',
        ),
    ]
