# Generated by Django 3.1.4 on 2021-05-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210401_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
